### ISSUE TITLE
ICS downloads only contain first booking per day and per room

### ISSUE THREAD

**Issue by gosogonzales** [unibonn/indico-bookings2ics#1]
Hi,

testing the get_indico_events_to_ics.py script on our indico server revealed that the ics files generated contain only the first booking in time per day and room. I guess there is a loop missing somewhere to loop over all events per room and day and to fill them all in the ics index by the room id. 

OS in use:
* Rocky Linux release 8.7 (Green Obsidian)

Packages in use:
* python39-3.9.13-2
* python3-requests-2.20.0-2.1
* libical-3.0.3-3
* python3-pytz-2017.2-9

How to reproduce:
*  python3 ./get_indico_events_to_ics.py
* Check the entries in the ./icalendars/*.ics files and compare with the values stored in the related indico server -> room booking

**Comment by gosogonzales** [comment]
I furthermore investigated the issue and it seems that in the function 

get_calendar(bookings)

The structure of bookings still contains all bookings, but in the loop inside that function, where booking is extracted as elements of bookings, there only the first entry is added to the calendar object as event.

**Comment by David-Berghaus** [comment]
Fixed in #2
